- routes/api.php
@HungThinh0710 I 've done. You can review it. Thank you.
> BE-5 Return profile's information

- app/Http/Controllers/RoleController.php
- app/Http/Requests/RoleRequest.php
- app/RolePermission.php
- database/seeds/PermissionTableSeeder.php
- routes/api.php
@HungThinh0710 I've done this ticket. Check it if you have time. Thank you.
> BE-10 Return a role's information

- app/Http/Controllers/RoleController.php
- app/Http/Requests/RoleRequest.php
- app/RolePermission.php
- database/seeds/PermissionTableSeeder.php
- routes/api.php
@HungThinh0710 Review it, please. Thank you.
> BE-17 Return list roles

- app/Http/Controllers/PermissionController.php
- app/Http/Controllers/RoleController.php
- app/Http/Requests/RoleRequest.php
- routes/api.php
@HungThinh0710 Let review it. Thank you.
> [BE-9] Add a role

- app/Http/Controllers/PermissionController.php
- routes/api.php
> BE-16 Return list permission

- app/Http/Controllers/RoleController.php
- app/Http/Controllers/UserController.php
@Nguyentrang197 Let's check it.
> [BE-6] Update findOrFail method

- app/Http/Controllers/PermissionController.php
- app/Http/Controllers/RoleController.php
- app/Http/Requests/RoleRequest.php
- app/Role.php
- routes/api.php
@HungThinh0710 Let take a look at my code. Thank you.
> [BE-11] Update a role and paginate list permission

- app/Http/Controllers/RoleController.php
- routes/api.php
@HungThinh0710 Check it, please.
> [BE-12] Delete roles

- app/Http/Controllers/RoleController.php
- app/Http/Controllers/UserController.php
- app/User.php
- routes/api.php
> BE-18 Return list users

- app/Http/Controllers/UserController.php
- app/Policies/ArticlePolicy.php
- app/Policies/CandidatePolicy.php
- app/Policies/InterviewPolicy.php
- app/Policies/InterviewerPolicy.php
- app/Policies/JobPolicy.php
- app/Policies/RolePolicy.php
- app/Policies/UserPolicy.php
- app/Providers/AuthServiceProvider.php
- app/Role.php
- app/User.php
- routes/api.php
@Nguyentrang197 Let's take a look my code.
> [BE-7] Add authorize for project

- app/Http/Controllers/UserController.php
- app/Http/Requests/CreateUserRequest.php
- app/Policies/UserPolicy.php
- app/Providers/AuthServiceProvider.php
- database/migrations/2019_07_01_065431_create_users_table.php
- database/seeds/ArticleTableSeeder.php
- database/seeds/CandidateTableSeeder.php
- database/seeds/CategoryTableSeeder.php
- database/seeds/InterviewTableSeeder.php
- database/seeds/InterviewerTableSeeder.php
- database/seeds/JobTableSeeder.php
- database/seeds/PermissionTableSeeder.php
- database/seeds/UserTableSeeder.php
- routes/api.php
> [BE-20] Add a user and update file Seeder

- app/Http/Controllers/JobController.php
- routes/api.php
@Nguyentrang197 Take a look my PR.
> [BE-24] Update API for Recruitment-Webapp

- app/Article.php
- app/Http/Controllers/ArticleController.php
- app/Http/Requests/ArticleRequest.php
- database/migrations/2019_07_01_070021_create_jobs_table.php
- database/migrations/2019_07_01_070142_create_articles_table.php
- database/migrations/2019_07_01_070228_create_candidates_table.php
- database/migrations/2019_07_01_070314_create_interviewers_table.php
- database/migrations/2019_07_12_034733_add_column_to_categories_table.php
- database/seeds/CategoryTableSeeder.php
- routes/api.php
@HungThinh0710 Can you help me check it?
> [BE-40] Add an article

- app/Http/Controllers/ArticleController.php
- routes/api.php
> [BE-43] Return list article

- app/Http/Controllers/ArticleController.php
- app/Http/Controllers/JobController.php
- app/Http/Requests/ArticleRequest.php
- routes/api.php
@Nguyentrang197  Please accept my PR.
> [BE-42] Create the API for deleting the article/many article

- app/Http/Controllers/ArticleController.php
- routes/api.php
@Nguyentrang197 Please take a look my PR.
> [BE-44] Create the API for showing an article

- app/Candidate.php
- app/Http/Controllers/CandidateController.php
- routes/api.php
@HungThinh0710 Let check my code.
> [BE-34] Create the API to return a candidate's information

- app/Http/Controllers/ArticleController.php
- routes/api.php
@HungThinh0710 Let check my code.
> [BE-58] Create the API to get list articles for guests

- app/Http/Controllers/CandidateController.php
- app/Http/Requests/CandidateRequest.php
- database/migrations/2019_07_12_034733_add_column_to_categories_table.php
- database/migrations/2019_07_18_023052_add_column_in_table_article_and_role.php
@HungThinh0710 Can you check my code.
> [BE-35] Create the API to delete a candidate/many candidates and update table 

- app/Http/Controllers/RoleController.php
- app/Http/Controllers/UserController.php
@HungThinh0710 Let check it again.
> [BE-61] Fix the API for deleting or updating role admin

- .gitignore
- app/Http/Controllers/CandidateController.php
- app/Services/CandidateService.php
- routes/api.php
@Nguyentrang197 Please help me check PR, thank you.
> [BE-36] Create the API to update the status of a candidate

- app/Category.php
- app/Http/Controllers/CategoryController.php
- app/Policies/CategoryPolicy.php
- app/Providers/AuthServiceProvider.php
- routes/api.php
@Nguyentrang197 Please check my PR.
> [BE-45] Create the API to return the list category for article

- database/migrations/2019_07_01_070021_create_jobs_table.php
- database/migrations/2019_07_01_070337_create_interviews_table.php
@HungThinh0710 I added some columns in the table, let check it.
> Add column in table jobs and interviews

- app/Http/Controllers/InterviewController.php
- app/Interview.php
Reverts HungThinh0710/recruitment-management#104
> Revert "[BE-47] Update add candidates and interviewers to interview"

- app/Http/Controllers/InterviewController.php
@HungThinh0710 Please check my code.
> [BE-49] Create the API to show an interview's information

- app/Http/Controllers/InterviewerController.php
@NguyenTrang197 Please help me check my PR.
> [BE-32] Create the API to delete an interviewer/many interviewers/all

- app/FormatArticle.php
- app/Http/Controllers/FormatArticleController.php
- app/Http/Requests/FormatArticleRequest.php
- database/migrations/2019_07_30_035613_create_format_article_table.php
- routes/api.php
@HungThinh0710 Help me review my PR.
> [BE-68] Create an API to show list format article

- app/FormatArticle.php
- app/Http/Controllers/FormatArticleController.php
- app/Http/Requests/FormatArticleRequest.php
- database/migrations/2019_07_30_035613_create_format_article_table.php
- routes/api.php
@Nguyentrang197 Please help me check my PR.
> [BE-66] Create an API to create the format for article

- app/Article.php
- app/Http/Controllers/ArticleController.php
- routes/api.php
@HungThinh0710 Help me check it.
> [BE-54] Create the API to get list articles related to the current article

- app/Http/Controllers/ArticleController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/CandidateController.php
- app/Http/Controllers/CategoryController.php
- app/Http/Controllers/InterviewerController.php
- app/Http/Controllers/JobController.php
- app/Http/Controllers/PermissionController.php
- app/Http/Controllers/RoleController.php
- app/Http/Controllers/UserController.php
- app/Interviewer.php
- routes/api.php
Reverts HungThinh0710/recruitment-management#133
> Revert [BE-73]

- app/Http/Controllers/ArticleController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/CategoryController.php
- app/Http/Controllers/InterviewerController.php
- app/Http/Controllers/JobController.php
- app/Http/Controllers/RoleController.php
- app/Interviewer.php
@HungThinh0710 Help me check it.
> [BE-74] Update the API for showing list all items

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/SessionController.php
- app/Http/Kernel.php
- app/Http/Requests/AuthRequest.php
- routes/api.php
Add: Get information user by session.
Fix: 429 Too many requests.
> Be session silent
